WeBankBlockchain/WeCross

build.gradle
src/main/resources/WeCrossContext-sample.xml
src/main/resources/web.xml

chang config filename

---

src/main/java/com/webank/wecross/exception/Exception.java
src/main/java/com/webank/wecross/exception/WeCrossException.java
src/main/java/com/webank/wecross/stub/bcos/BCOSContractResource.java

support simple arguments

---

src/main/java/com/webank/wecross/bcos/BCOSResource.java
src/main/java/com/webank/wecross/bcos/BCOSStub.java
src/main/java/com/webank/wecross/core/NetworkManager.java
src/main/java/com/webank/wecross/network/Network.java
src/main/java/com/webank/wecross/resource/Path.java
src/main/java/com/webank/wecross/resource/Resource.java
src/main/java/com/webank/wecross/restserver/RestRequest.java
src/main/java/com/webank/wecross/restserver/RestfulService.java
src/main/java/com/webank/wecross/stub/Stub.java
src/test/java/com/webank/wecross/test/HostTest.java

change uri to path

---

build.gradle
src/main/java/com/webank/wecross/network/config/NetworkConfig.java
src/main/java/com/webank/wecross/resource/request/TransactionRequest.java
src/main/java/com/webank/wecross/resource/response/TransactionResponse.java
src/main/java/com/webank/wecross/stub/jdchain/JDChainContractResource.java
src/main/java/com/webank/wecross/stub/jdchain/config/JDChainStubConfig.java
src/test/resources/application.yml

add jd chain invoke method

---

src/main/java/com/webank/wecross/exception/Status.java
src/main/java/com/webank/wecross/restserver/response/GetDataResponse.java
src/main/java/com/webank/wecross/stub/jdchain/JDChainContractResource.java

add get data interface for jdchain service

add get data interface for jdchain service

---

src/main/java/com/webank/wecross/stub/jdchain/JDChainResource.java

add ignore for variables

---

src/main/java/com/webank/wecross/restserver/response/TransactionResponse.java
src/main/java/com/webank/wecross/stub/remote/RemoteResource.java

Bug fix: Remote resource pass calling error directly (Just retry p2p error)

Bug fix: Remote resource pass calling error directly 

---

build.gradle
src/main/java/com/webank/wecross/Service.java

use bc as default security provider

use bc as default security provider

---

scripts/build_wecross.sh
src/main/java/com/webank/wecross/storage/BlockHeaderStorage.java
src/main/java/com/webank/wecross/storage/RocksDBBlockHeaderStorage.java
src/main/java/com/webank/wecross/zone/ZoneManager.java

Release rc2 fix rocksdb

---

scripts/add_chain.sh

去掉前：
[jason@RUAN:~/wecross/routers-payment/127.0.0.1-8250-25500]$ bash add_chain.sh -t BCOS2.0 -n bcos
Initializing StubManager...
operator: connection type: BCOS2.0 path: conf/chains//bcos
去掉后：
operator: connection type: BCOS2.0 path: conf/chains/bcos

去掉多余的路径斜杠。

---

src/main/java/com/webank/wecross/config/WeCrossHostConfig.java
src/main/java/com/webank/wecross/config/XATransactionManagerConfig.java
src/main/java/com/webank/wecross/host/WeCrossHost.java
src/main/java/com/webank/wecross/network/rpc/URIHandlerDispatcher.java
src/main/java/com/webank/wecross/network/rpc/handler/XATransactionHandler.java
src/test/java/com/webank/wecross/test/rpc/URIHandlerDispatcherTest.java

add xa transaction rpc handler

add xa transaction rpc handler

---

build.gradle
src/main/java/com/webank/wecross/config/AccountManagerConfig.java
src/main/java/com/webank/wecross/config/StubManagerConfig.java
src/main/java/com/webank/wecross/config/ZoneManagerConfig.java
src/main/java/com/webank/wecross/config/ZonesConfig.java
src/main/java/com/webank/wecross/host/WeCrossHost.java
src/main/java/com/webank/wecross/peer/Peer.java
src/main/java/com/webank/wecross/remote/RemoteConnection.java
src/main/java/com/webank/wecross/resource/Resource.java
src/main/java/com/webank/wecross/resource/ResourceDetail.java
src/main/java/com/webank/wecross/restserver/response/StubResponse.java
src/main/java/com/webank/wecross/routine/htlc/HTLCResource.java
src/main/java/com/webank/wecross/stub/Connection.java
src/main/java/com/webank/wecross/stub/Request.java
src/main/java/com/webank/wecross/stubmanager/StubManager.java
src/main/java/com/webank/wecross/zone/Chain.java
src/main/java/com/webank/wecross/zone/ChainInfo.java
src/main/java/com/webank/wecross/zone/ZoneManager.java
src/test/java/com/webank/wecross/test/zone/ZoneManagerTest.java

1. Sync resource once at connection resource updated
2. Debug sendTransaction with proxy

Update sync resource logic and sendTransaction with proxy logic

---

src/main/java/com/webank/wecross/network/rpc/netty/URIMethod.java

support call chain or resource

support call chain or resource

---

src/main/java/com/webank/wecross/network/NetworkCallback.java
src/main/java/com/webank/wecross/network/p2p/P2PProcessor.java
src/main/java/com/webank/wecross/network/p2p/P2PService.java
src/main/java/com/webank/wecross/network/rpc/handler/ListAccountsURIHandler.java
src/main/java/com/webank/wecross/network/rpc/handler/ListResourcesURIHandler.java
src/main/java/com/webank/wecross/network/rpc/handler/ListStubsURIHandler.java
src/main/java/com/webank/wecross/network/rpc/handler/ResourceURIHandler.java
src/main/java/com/webank/wecross/network/rpc/netty/handler/HttpServerHandler.java
src/main/java/com/webank/wecross/utils/ObjectMapperFactory.java

add ObjectMapperFactory to getObjectMapper in the com/webank/wecross/utils

add ObjectMapperFactory to getObjectMapper in the com/webank/wecross/utils

---

.ci/ci_cross_groups_demo_check.sh
.ci/ci_demo_check.sh
.ci/ci_performance_test.sh
build.gradle
demo/build.sh
demo/build_cross_groups.sh
demo/htlc_config.sh
scripts/build_wecross.sh
src/main/java/com/webank/wecross/config/AccountManagerConfig.java
src/main/java/com/webank/wecross/config/ZonesConfig.java
src/main/java/com/webank/wecross/exception/WeCrossException.java
src/main/java/com/webank/wecross/network/p2p/P2PProcessor.java
src/main/java/com/webank/wecross/peer/Peer.java
src/main/java/com/webank/wecross/utils/HashUtils.java
src/main/java/com/webank/wecross/utils/Sha256Utils.java
src/main/java/com/webank/wecross/zone/Chain.java
src/main/java/com/webank/wecross/zone/ChainInfo.java
src/main/java/com/webank/wecross/zone/ZoneManager.java
src/main/resources/wecross-sample.toml
src/test/java/com/webank/wecross/test/zone/ZoneManagerTest.java

1. verify chain checksum
2. add more check during booting up
3. add more help and delete unused configure

Fix many bugs

---

src/main/java/com/webank/wecross/routine/xa/XATransactionInfo.java
src/main/java/com/webank/wecross/routine/xa/XATransactionManager.java
src/main/java/com/webank/wecross/routine/xa/XATransactionStep.java
src/main/java/com/webank/wecross/stub/Path.java
src/main/java/com/webank/wecross/zone/ZoneManager.java

fix gettransactioninfo error

---

src/main/java/com/webank/wecross/config/AccountManagerConfig.java
src/main/java/com/webank/wecross/config/ResourceThreadPoolConfig.java
src/main/java/com/webank/wecross/config/StubManagerConfig.java
src/main/java/com/webank/wecross/host/WeCrossHost.java
src/main/java/com/webank/wecross/network/p2p/P2PProcessor.java
src/main/java/com/webank/wecross/network/p2p/P2PService.java
src/main/java/com/webank/wecross/network/p2p/netty/HeartBeatProcessor.java
src/main/java/com/webank/wecross/network/p2p/netty/NettyBootstrap.java
src/main/java/com/webank/wecross/network/p2p/netty/NettyService.java
src/main/java/com/webank/wecross/network/p2p/netty/RequestProcessor.java
src/main/java/com/webank/wecross/network/p2p/netty/ResponseProcessor.java
src/main/java/com/webank/wecross/network/p2p/netty/channel/handler/ChannelHandler.java
src/main/java/com/webank/wecross/network/p2p/netty/message/MessageCallBack.java
src/main/java/com/webank/wecross/network/rpc/URIHandlerDispatcher.java
src/main/java/com/webank/wecross/network/rpc/handler/ResourceURIHandler.java
src/main/java/com/webank/wecross/network/rpc/netty/handler/HttpServerHandler.java
src/main/java/com/webank/wecross/routine/htlc/HTLCScheduler.java
src/main/java/com/webank/wecross/utils/ConfigUtils.java
src/main/java/com/webank/wecross/zone/Chain.java
src/main/java/com/webank/wecross/zone/ZoneManager.java

Optimize log printing

---

src/main/java/com/webank/wecross/Generator.java
src/main/java/com/webank/wecross/resource/Resource.java

提交spring注解上下文的成员变量化以及日志打印改造 #276

< perf>(Resource): replace callback with lambda

---

src/main/java/com/webank/wecross/network/UriDecoder.java
src/main/java/com/webank/wecross/network/rpc/URIHandlerDispatcher.java
src/main/java/com/webank/wecross/network/rpc/handler/ConnectionURIHandler.java
src/main/java/com/webank/wecross/network/rpc/netty/handler/HttpServerHandler.java
src/main/java/com/webank/wecross/peer/PeerManager.java
src/main/java/com/webank/wecross/stubmanager/MemoryBlockManager.java

add page for listChains and listPeers

add page for listChains and listPeers

---

src/main/java/com/webank/wecross/config/AuthFilterConfig.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<feat>(login): add changePassword interface

---

demo/fabric/build.sh

start fabric-samples as -n mode (do not deploy the chaincode mycc), and detach remove_mycc

<perf> start fabric-samples as -n mode

---

scripts/create_cert.sh
src/main/java/com/webank/wecross/network/client/NettyAsyncHttpClientEngine.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<feat>(cert): support rsa cert

---

scripts/start.sh

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>: add -Djdk.disabled.namedCurves and -Djdk.sunec.disableNative to start.sh

---

demo/bcos/build.sh
demo/bcos/build_gm.sh
demo/build.sh
demo/build_cross_all.sh
demo/build_cross_gm.sh
demo/build_cross_groups.sh

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<feat>(demo): add -f optional to set bcos version

---

scripts/download_account_manager.sh
src/main/java/com/webank/wecross/common/WeCrossDefault.java
src/main/java/com/webank/wecross/config/BlockVerifierTomlConfig.java
src/main/java/com/webank/wecross/config/ZonesConfig.java
src/main/java/com/webank/wecross/utils/ConfigUtils.java
src/main/java/com/webank/wecross/zone/ZoneManager.java
src/test/java/com/webank/wecross/test/config/BlockVerifierTomlConfigTest.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>(BlockVerifier): fix fabric properties, check verifiers before router running. 

---

demo/build_cross_groups.sh
src/main/java/com/webank/wecross/network/client/NettyAsyncHttpClientEngine.java
src/main/java/com/webank/wecross/network/rpc/authentication/RemoteAuthFilter.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>: fix the problem there has no response when account manager crash

---

build.gradle
scripts/deploy_system_contract.sh
src/main/java/com/webank/wecross/stubmanager/MemoryBlockManager.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>: fix gm ssl unusable bug

---

src/main/java/com/webank/wecross/stubmanager/MemoryBlockManager.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

fix timeout error when getBlock failed

---

demo/build_cross_all.sh
demo/build_cross_gm.sh
demo/build_cross_groups.sh

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<feat>(demo): add java env check

---

build.gradle

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

update gradle version

---

.github/workflows/publish_binary.yml

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

update upload version

---

demo/build.sh
demo/build_cross_all.sh
demo/build_cross_channel.sh
demo/build_cross_gm.sh
demo/build_cross_groups.sh
scripts/start.sh

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>(jdk): add java version check

---

demo/fabric2/add_channel.sh
demo/fabric2/build.sh
demo/fabric2/clear.sh
demo/fabric2/update-channel-tx.sh

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

Add fabric2.x demo build

---

scripts/upgrade_account_manager.sh
scripts/upgrade_console.sh
scripts/upgrade_wecross.sh

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<feat>(upgrade): add wecross upgrade scripts

---

.github/workflows/publish_scripts.yml

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

push upgradle_xxx scripts on tag when publish

---

src/main/java/com/webank/wecross/zone/Chain.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

fix null exception caused by empty connections

---

build.gradle

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>(gradle):update spring-boot-xxx version to 2.3.9

---

scripts/start.sh
src/main/java/com/webank/wecross/Service.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>: exit the program when start failed

---

build.gradle
src/main/java/com/webank/wecross/account/AccountManager.java
src/main/java/com/webank/wecross/account/RouterLoginAccountContext.java
src/main/java/com/webank/wecross/config/AccountManagerConfig.java
src/main/java/com/webank/wecross/config/AccountManagerEngineConfig.java
src/main/java/com/webank/wecross/config/AdminContextConfig.java
src/main/java/com/webank/wecross/config/ConfigReaderConfig.java
src/main/java/com/webank/wecross/network/client/ClientConnection.java
src/main/java/com/webank/wecross/network/client/NettyAsyncHttpClientEngine.java
src/main/java/com/webank/wecross/network/rpc/netty/handler/HttpServerHandler.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

allow name token auth for account manager

---

src/main/java/com/webank/wecross/account/AccountAccessControlFilterFactory.java
src/main/java/com/webank/wecross/account/AccountManager.java
src/main/java/com/webank/wecross/account/UniversalAccountFactory.java
src/main/java/com/webank/wecross/common/WeCrossDefault.java
src/main/java/com/webank/wecross/network/rpc/handler/SystemInfoHandler.java
src/main/java/com/webank/wecross/network/rpc/handler/TransactionURIHandler.java

(cherry picked from commit 1f7e8f19e7c24c0e8200749edafaba71cecc024b)
---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<perf>(Access Control): Support to get enableAccessControl switch info

---

demo/fabric/build.sh

<fix>(demo): fix demo fabric build.sh incidental error bug in macOS env.

---

src/main/java/com/webank/wecross/account/AccountManager.java
src/main/java/com/webank/wecross/config/AccountManagerConfig.java
src/main/java/com/webank/wecross/config/AuthFilterConfig.java
src/main/java/com/webank/wecross/network/rpc/authentication/RemoteAuthFilter.java
src/main/java/com/webank/wecross/network/rpc/netty/handler/HttpServerHandler.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

fix name token auth failed

---

.ci/ci_cross_fabric2_demo_check.sh
.github/workflows/ci_check_bcos_fabric2.yml
demo/clear.sh
demo/fabric/build.sh
demo/fabric2/build.sh
demo/fabric2/start.sh
demo/fabric2/stop.sh
scripts/download_plugin.sh
src/main/java/com/webank/wecross/common/WeCrossDefault.java

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

Update scripts for supporting fabric2 start, stop and verifier

---

.github/workflows/ci_check_bcos_fabric2.yml
.github/workflows/publish_binary.yml
demo/clear.sh
demo/fabric2/build.sh

(cherry picked from commit 0d48c2bd7d14f5a21534c19e09814fb235214488)
---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>(demo): Fix fabric2 deploy bug

---

demo/fabric/build.sh

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>: Fix fabric byfn.sh -i bug, add go command check

---

build.gradle

---
---
**标题**
不超过80个字符，英文
格式：
```
```
示例：
```
```
**type**
- feat: 新功能
- fix: 修复bug
- test: 增加测试
- docs: 文档
- merge: 代码合并
**scope**
**subject**

<fix>(project): upgrade project spring, bouncycastle deps version.
